trigger:
  - master # or the name of your main branch
  - feat/*

pool:
  vmImage: ubuntu-latest

steps:
  # Prepare Analysis Configuration task
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'sonar-qube'
      scannerMode: 'Other'
      extraProperties: 'sonar.projectKey=data-lab_profile-server_AYtfoEGk6jcPUmMEnhcF'

  # Publish Quality Gate Result task
  - task: SonarQubePublish@5
    inputs:
      pollingTimeoutSec: '300'

  - task: Gradle@3
    inputs:
      workingDirectory: '$(system.defaultWorkingDirectory)'
      gradleWrapperFile: 'gradlew'
      tasks: 'prodBuild'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      sonarQubeRunAnalysis: true

  - task: CopyFiles@2
    inputs:
      contents: '**/*.jar'
      targetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'